### ISSUE TITLE
質問：課題 202_02 文字列と数値を結合

### ISSUE THREAD

**Issue by TM-k-nakagawa** [TM-k-nakagawa/Practice.java#2]
100円のバナナを25個、300円の桃を25個買ったら、合計10,000円になりました。Javaとプログラムを書くのですが、
10000円の部分で、問題の表記は10,000円でした。

この場合、
10,000円と出力されるように記述するべきでしょうか？
それとも10000円で出力されるように記述するべきでしょうか？

**Comment by HyunwookPark** [comment]
@TM-k-nakagawa 
10,000円と出力してください。^^

**Comment by TM-k-nakagawa** [comment]
@HyunwookPark 
ありがとうございます。聞かなかったら、10000円で終了しておりました
