### ISSUE TITLE
質問：202_05　文字数カウントについて

### ISSUE THREAD

**Issue by TM-k-nakagawa** [TM-k-nakagawa/Practice.java#4]
現状、202_05の問題で以下の記述を書いております。

```java
public class Practice202_05 {
    public static void main(String[] args) {
        String text = "1234567890\r\n1234567890";
        System.out.println(text);
        int num_text = text.length();
        System.out.println(num_text);
    }
}
```

コンパイルして
1234567890
1234567890
22と表示されたのですが、

すべて文字をカウントしたら10×2+4で24だと考えてコンパイルしたら22となりました。
/はカウントされないと考えて大丈夫でしょうか？

**Comment by TM-k-nakagawa** [comment]
後回しにして、現状のコードでコミットプッシュします。

**Comment by HyunwookPark** [comment]
@TM-k-nakagawa 

> すべて文字をカウントしたら10×2+4で24だと考えてコンパイルしたら22となりました。
> /はカウントされないと考えて大丈夫でしょうか？

そのカウント方法でOKです。
改行はエスケープシーケンスのひとつです。
`\r`や`\n`で一文字です。

**Comment by TM-k-nakagawa** [comment]
@HyunwookPark 
ありがとうございます。
